/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airport_GUI;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Airport_GUI.Conn.connection;
import java.awt.Color;
import javax.swing.JOptionPane;
import splashscreen.SplashScreen;

/**
 *
 * @author xiiMody
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
          // TODO add your handling code here:
         jButton8.setVisible(false);
        tt2.setVisible(false);
        tt1.setVisible(false);
        jLabel15.setVisible(false);
        jLabel11.setVisible(false);
        jLabel7.setVisible(false);
        jButton9.setVisible(false);
       //00000000000001
        jLabel8.setVisible(true);
        jButton5.setVisible(true);
        jPasswordField1.setVisible(true);
        jLabel12.setVisible(true);
        jTextField18.setVisible(true);
        jLabel14.setVisible(true);
        jButton6.setVisible(true);
        jLabel9.setVisible(true);
        jLabel6.setVisible(true);
       
        jPanel1.setBackground(Color.decode("#14275A"));
        jPanel2.setBackground(Color.decode("#E8EBF2"));
//        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        tt2 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 39, 90));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(232, 235, 242));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 235, 242));
        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, -1));

        jButton5.setBackground(new java.awt.Color(232, 235, 242));
        jButton5.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(20, 39, 90));
        jButton5.setText("Login");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 160, 40));

        jLabel14.setBackground(new java.awt.Color(232, 235, 242));
        jLabel14.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(232, 235, 242));
        jLabel14.setText("Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 130, 30));

        jTextField18.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jTextField18.setDisabledTextColor(new java.awt.Color(153, 102, 0));
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 270, 30));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 270, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 39, 90));
        jLabel6.setText("Register ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(20, 39, 90));
        jLabel9.setText("In our system");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jButton7.setBackground(new java.awt.Color(232, 182, 86));
        jButton7.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(20, 39, 90));
        jButton7.setText("Sign Up");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 240, -1));
        jPanel2.add(tt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 280, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 235, 242));
        jLabel15.setText("Password");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 30));

        tt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt1ActionPerformed(evt);
            }
        });
        jPanel2.add(tt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 280, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 235, 242));
        jLabel11.setText("Username");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jButton8.setBackground(new java.awt.Color(232, 235, 242));
        jButton8.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(20, 39, 90));
        jButton8.setText("Sign Up");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 170, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 235, 242));
        jLabel7.setText("Sign up");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jButton6.setBackground(new java.awt.Color(232, 235, 242));
        jButton6.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(20, 39, 90));
        jButton6.setText("Sign Up");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 560, 550));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 182, 86));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(232, 235, 242));
        jLabel12.setText("Sign In");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(20, 39, 90));
        jLabel13.setText("Login ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(20, 39, 90));
        jLabel16.setText("In our system");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jButton9.setBackground(new java.awt.Color(232, 235, 242));
        jButton9.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(20, 39, 90));
        jButton9.setText("Login ");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try {
           ResultSet rs =  Conn.stmt.executeQuery("Select * from Admins where Username = '"+jTextField18.getText()+"'and password = '"+jPasswordField1.getText()+"'");
//            Conn.stmt.execute("Select * from Admins where Username = '"+jTextField18.getText()+"'and password = '"+jPasswordField1.getText()+"'");
            int size = 0;
            while(rs.next()){
                size++;
            }
    
            if(size!=1){
                JOptionPane.showMessageDialog(null, "Wrong username or password");
            }else{
//                new Employees().setVisible(true);
                    new SplashScreen().setVisible(true);
                dispose();
//                this.setVisible(false);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jLabel8.setVisible(false);
        jButton5.setVisible(false);
        jPasswordField1.setVisible(false);
        jLabel12.setVisible(false);
        jTextField18.setVisible(false);
        jLabel14.setVisible(false);
        jButton6.setVisible(false);
        jLabel9.setVisible(false);
        jLabel6.setVisible(false);
        jPanel2.setBackground(Color.decode("#14275A"));
        jPanel1.setBackground(Color.decode("#E8EBF2"));
        jButton8.setVisible(true);
        tt2.setVisible(true);
        tt1.setVisible(true);
        jLabel15.setVisible(true);
        jLabel11.setVisible(true);
        jLabel7.setVisible(true);
        jButton9.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         try {
           ResultSet rs =  Conn.stmt.executeQuery("Select * from Admins where Username = '"+jTextField18.getText()+"'and password = '"+jPasswordField1.getText()+"'");
//            Conn.stmt.execute("Select * from Admins where Username = '"+jTextField18.getText()+"'and password = '"+jPasswordField1.getText()+"'");
            int size = 0;
            while(rs.next()){
                size++;
            }
    
            if(size!=1){
                JOptionPane.showMessageDialog(null, "Wrong username or password");
            }else{
//                new Employees().setVisible(true);
                    new SplashScreen().setVisible(true);
                dispose();
//                this.setVisible(false);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void tt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tt1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            if(tt1.getText().equals("") || tt2.getText().equals("")){

                JOptionPane.showMessageDialog(null, "Please Enter all values" );
                return;
            }

            PreparedStatement statement = connection.prepareStatement("insert into Admins(Username,password)\n" +
                "values('" + tt1.getText() + "', '" + tt2.getText()+ "')",java.sql.Statement.RETURN_GENERATED_KEYS);

            int affectedRows = statement.executeUpdate();

            if (affectedRows == 0) {
                JOptionPane.showMessageDialog(null, "Adding Admin failed" );
                return;
            }

            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {

                    JOptionPane.showMessageDialog(null, "Inserted succefully and The Admin Code is : " + generatedKeys.getLong(1));

                }
                else {
                    JOptionPane.showMessageDialog(null, "Adding Admin failed" );
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            if(tt1.getText().equals("") || tt2.getText().equals("")){

                JOptionPane.showMessageDialog(null, "Please Enter all values" );
                return;
            }

            PreparedStatement statement = connection.prepareStatement("insert into Admins(Username,password)\n" +
                "values('" + tt1.getText() + "', '" + tt2.getText()+ "')",java.sql.Statement.RETURN_GENERATED_KEYS);

            int affectedRows = statement.executeUpdate();

            if (affectedRows == 0) {
                JOptionPane.showMessageDialog(null, "Adding Admin failed" );
                return;
            }

            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {

                    JOptionPane.showMessageDialog(null, "Inserted succefully and The Admin Code is : " + generatedKeys.getLong(1));

                }
                else {
                    JOptionPane.showMessageDialog(null, "Adding Admin failed" );
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         jButton8.setVisible(false);
        tt2.setVisible(false);
        tt1.setVisible(false);
        jLabel15.setVisible(false);
        jLabel11.setVisible(false);
        jLabel7.setVisible(false);
        jButton9.setVisible(false);
       //00000000000001
        jLabel8.setVisible(true);
        jButton5.setVisible(true);
        jPasswordField1.setVisible(true);
        jLabel12.setVisible(true);
        jTextField18.setVisible(true);
        jLabel14.setVisible(true);
        jButton6.setVisible(true);
        jLabel9.setVisible(true);
        jLabel6.setVisible(true);
       
        jPanel1.setBackground(Color.decode("#14275A"));
        jPanel2.setBackground(Color.decode("#E8EBF2"));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jButton5.setBackground(Color.decode("#14275A"));
        jButton5.setForeground(Color.decode("#E8EBF2"));
        
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
         jButton5.setBackground(Color.decode("#E8EBF2"));
         jButton5.setForeground(Color.decode("#14275A"));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        jButton9.setBackground(Color.decode("#14275A"));
        jButton9.setForeground(Color.decode("#E8EBF2"));
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        // TODO add your handling code here:
         jButton9.setBackground(Color.decode("#E8EBF2"));
         jButton9.setForeground(Color.decode("#14275A"));
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jButton6.setBackground(Color.decode("#14275A"));
        jButton6.setForeground(Color.decode("#E8EBF2"));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        jButton6.setBackground(Color.decode("#E8EBF2"));
         jButton6.setForeground(Color.decode("#14275A"));
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
        jButton8.setBackground(Color.decode("#14275A"));
        jButton8.setForeground(Color.decode("#E8EBF2"));
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
        jButton8.setBackground(Color.decode("#E8EBF2"));
         jButton8.setForeground(Color.decode("#14275A"));
    }//GEN-LAST:event_jButton8MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField tt1;
    private javax.swing.JPasswordField tt2;
    // End of variables declaration//GEN-END:variables
}
